name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/**"
      - "**/*.md"
      - ".gitignore"
      - ".env.example"
      - "LICENSE"
      - ".prettierrc"
      - ".eslintrc.*"
      - ".editorconfig"

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      CLERK_SIGNING_SECRET: ${{ secrets.CLERK_SIGNING_SECRET }}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
      NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: "/"
      NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: "/"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      MUX_TOKEN_ID: ${{ secrets.MUX_TOKEN_ID }}
      MUX_TOKEN_SECRET: ${{ secrets.MUX_TOKEN_SECRET }}
      MUX_SIGNING_SECRET: ${{ secrets.MUX_SIGNING_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.bun/install/cache
            .turbo
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
          lookup-only: true

      - name: Install Turbo globally
        run: bun install -g turbo

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup Vercel CLI
        run: bun install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: turbo build --cache-dir=".turbo" --api="https://api.vercel.com"
